import matplotlib.pyplot as plt
import numpy as np

def plot_result(data, log_path):
    plt.figure()
    plt.subplot(3,1,1)
    plt.plot(np.clip(data.train_loss,-np.inf,2*np.mean(np.abs(data.train_loss))),linewidth=1.)
    plt.title('train loss '+str(data.train_loss[-1]))
    plt.subplot(3,1,2)
    plt.plot(np.clip(data.test_mse,-np.inf,2*np.mean(np.abs(data.test_mse))),linewidth=1.)
    plt.title('test mse '+str(data.test_mse[-1]))
    plt.subplot(3,1,3)
    plt.plot(np.clip(data.test_rmse,-np.inf,2*np.mean(np.abs(data.test_rmse))),linewidth=1.)
    plt.title('test rmse '+str(data.test_rmse[-1]))
    plt.savefig(log_path+'curve.png')
    plt.close()

    plt.figure()
    plot1, = plt.plot(data.pred_train[::100],linewidth=1.)
    plot2, = plt.plot(data.label_train[::100],linewidth=1.)
    plt.legend([plot1,plot2],['pred','label'])
    plt.title('final train result')
    plt.savefig(log_path+'final_train.png')
    plt.close()
    plt.figure()
    plot1, = plt.plot(data.pred_test[::100],linewidth=1.)    
    plot2, = plt.plot(data.label_test[::100],linewidth=1.)
    plt.legend([plot1,plot2],['pred','label'])
    plt.title('final test result')
    plt.savefig(log_path+'final_test.png')
    plt.close()